# Codecov Configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "demo/**/*"
  - "scripts/**/*"
  - "**/__init__.py"
  - "**/conftest.py"

flags:
  unittests:
    paths:
      - src/valerie/
    carryforward: true
